#!/bin/sh

if [ -z "$CACHE_DIR" ] \
    || [ -z "$RCLONE_CONFIG" ] \
    || [ -z "$RCLONE_INCLUDE_FROM" ] \
    || [ -z "$RCLONE_TARGET" ]
then
    echo 'Requires CACHE_DIR, RCLONE_CONFIG, RCLONE_INCLUDE_FROM and RCLONE_TARGET to be set'
    exit 1
fi

if [ -n "$PRUNE" ]; then
    echo 'Pruning remote cache'
    rclone_cmd=sync
else
    rclone_cmd=copy
fi

set -e
set -x

mkdir -p "$CACHE_DIR"

rsync \
    -vh \
    -rlptH \
    --safe-links \
    --delete-delay \
    --delay-updates \
    rsync://mirror.23m.com/archlinux/ "$CACHE_DIR"/

rclone "$rclone_cmd" \
    -v \
    --config="$RCLONE_CONFIG" \
    --include-from="$RCLONE_INCLUDE_FROM" \
    --copy-links \
    "$CACHE_DIR"/ \
    "$RCLONE_TARGET"/
