#!/bin/sh

if [ -z "$CACHE_DIR" ] || [ -z "$RCLONE_CONFIG" ] || [ -z "$RCLONE_TARGET" ]; then
    echo 'Requires CACHE_DIR, RCLONE_CONFIG and RCLONE_TARGET to be set'
    exit 1
fi

set -e

echo 'Creating cache dir ...'
mkdir -p "$CACHE_DIR"

echo 'Syncing arch repository from mirror ...'
rsync \
    -vrlptH \
    --safe-links \
    --delete-delay \
    --delay-updates \
    rsync://mirror.23m.com/archlinux/ "$CACHE_DIR"/

echo 'Syncing arch repository to s3 ...'
rclone sync -v --copy-links --config="$RCLONE_CONFIG" "$CACHE_DIR"/ "$RCLONE_TARGET"/
