name: Update dockerfile dependencies

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  backup-tools-borg:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v6

    - name: Run argus
      run: >-
        docker run --rm
        -v ./:/work
        --env=GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        --workdir=/work
        ghcr.io/st3iny/argus:main
        --job=backup-tools/borg
        --job-log=argus-job-log.json

    - name: Extract argus log
      id: job-log
      run: |
        echo "FROM=$(jq -r '."backup-tools/borg".from' argus-job-log.json)" >> "$GITHUB_OUTPUT"
        echo "TO=$(jq -r '."backup-tools/borg".to' argus-job-log.json)" >> "$GITHUB_OUTPUT"

    - name: Create PR
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: "backup-tools: bump borg from ${{ steps.job-log.outputs.FROM }} to ${{ steps.job-log.outputs.TO }}"
        branch: backup-tools-borg
        title: "backup-tools: bump borg from ${{ steps.job-log.outputs.FROM }} to ${{ steps.job-log.outputs.TO }}"
        body: ""
        reviewers: st3iny
        add-paths: backup-tools/Dockerfile

  backup-tools-rclone:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v6

    - name: Run argus
      run: >-
        docker run --rm
        -v ./:/work
        --env=GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        --workdir=/work
        ghcr.io/st3iny/argus:main
        --job=backup-tools/rclone
        --job-log=argus-job-log.json

    - name: Extract argus log
      id: job-log
      run: |
        echo "FROM=$(jq -r '."backup-tools/rclone".from' argus-job-log.json)" >> "$GITHUB_OUTPUT"
        echo "TO=$(jq -r '."backup-tools/rclone".to' argus-job-log.json)" >> "$GITHUB_OUTPUT"

    - name: Create PR
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: "backup-tools: bump rclone from ${{ steps.job-log.outputs.FROM }} to ${{ steps.job-log.outputs.TO }}"
        branch: backup-tools-rclone
        title: "backup-tools: bump rclone from ${{ steps.job-log.outputs.FROM }} to ${{ steps.job-log.outputs.TO }}"
        body: ""
        reviewers: st3iny
        add-paths: backup-tools/Dockerfile
